// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package certificate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IstioCertificateServiceClient is the client API for IstioCertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IstioCertificateServiceClient interface {
	// Using provided CSR, returns a signed certificate.
	CreateCertificate(ctx context.Context, in *IstioCertificateRequest, opts ...grpc.CallOption) (*IstioCertificateResponse, error)
}

type istioCertificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIstioCertificateServiceClient(cc grpc.ClientConnInterface) IstioCertificateServiceClient {
	return &istioCertificateServiceClient{cc}
}

var istioCertificateServiceCreateCertificateStreamDesc = &grpc.StreamDesc{
	StreamName: "CreateCertificate",
}

func (c *istioCertificateServiceClient) CreateCertificate(ctx context.Context, in *IstioCertificateRequest, opts ...grpc.CallOption) (*IstioCertificateResponse, error) {
	out := new(IstioCertificateResponse)
	err := c.cc.Invoke(ctx, "/istio.v1.auth.IstioCertificateService/CreateCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IstioCertificateServiceService is the service API for IstioCertificateService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterIstioCertificateServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type IstioCertificateServiceService struct {
	// Using provided CSR, returns a signed certificate.
	CreateCertificate func(context.Context, *IstioCertificateRequest) (*IstioCertificateResponse, error)
}

func (s *IstioCertificateServiceService) createCertificate(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IstioCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.CreateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/istio.v1.auth.IstioCertificateService/CreateCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.CreateCertificate(ctx, req.(*IstioCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterIstioCertificateServiceService registers a service implementation with a gRPC server.
func RegisterIstioCertificateServiceService(s grpc.ServiceRegistrar, srv *IstioCertificateServiceService) {
	srvCopy := *srv
	if srvCopy.CreateCertificate == nil {
		srvCopy.CreateCertificate = func(context.Context, *IstioCertificateRequest) (*IstioCertificateResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method CreateCertificate not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "istio.v1.auth.IstioCertificateService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "CreateCertificate",
				Handler:    srvCopy.createCertificate,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "certificate/ca.proto",
	}

	s.RegisterService(&sd, nil)
}
